# Adwaita Dark — Foot Terminal Theme
[colors]
background=1d1d1d
foreground=ffffff

regular0=1d1d1d
regular1=c01c28
regular2=2ec27e
regular3=e5a50a
regular4=1c71d8
regular5=9141ac
regular6=12a3b4
regular7=c0bfbc

bright0=5c6370
bright1=ed333b
bright2=57e389
bright3=f8e45c
bright4=4a8fd8
bright5=c061cb
bright6=4fd2e4
bright7=ffffff

selection-foreground=ffffff
selection-background=2b4e7b
